# Site settings
title: Demystifying data
description: Cor Zuurmond
header_img: /assets/img/home.jpeg
baseurl:
owner: Cor
published_at: 2021

# Sidebar settings
sidebar: true
sidebar_avatar: /assets/img/avatar.jpeg
sidebar_about_description: Data Demystifier @ GoDataDriven

# SNS settings
RSS:                true
email:              hello@demystifyingdata.io
github_username:    JCZuurmond
#zhihu_username:     na
#weibo_username:     na
linkedin_username:  cor-zuurmond
#twitter_username:   na
#facebook_username:  na

# Uncomment the line below if you use this theme as a GitHub Page's remote theme.
remote_theme: lynn9388/huxpro

# Google Analytics settings (https://analytics.google.com/)
#ga_measurement_id: UA-138531028-1

# Comments settings (https://utteranc.es/)
# You must use your own repository, otherwise it won't work.
comments_repository: jczuurmond/comments

# Build settings
paginate: 10
timezone: Europe/Amsterdam
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
collections:
  pages:
    output: true
    permalink: /:path/
defaults:
  - scope:
      path: _posts
    values:
      layout: post
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - rouge
